security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: true
            logout:       true
            form_login:
                provider: fos_userbundle
                login_path: /login
                check_path: /login_check
                csrf_provider: form.csrf_provider
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                login_path:        /login
                use_forward:       false
                failure_path:      /login
                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge
            remember_me:
                  key:      oi4fgsl0562fg36hb4g3kibnewrfd
                  lifetime: 4147200
                  path:     /
                  domain:   ~
#        main:
#            pattern: ^/
#            anonymous: ~
#            logout: true
#            form_login:
#                  provider: fos_userbundle
#                  csrf_provider: form.csrf_provider
#                  login_path:     /login
#                  use_forward:    false
#                  check_path:     /login_check
#                  failure_path:   null
#            remember_me:
#                  key:      oi4fgsl0562fg36hb4g3kibnewrfd
#                  lifetime: 4147200
#                  path:     /
#                  domain:   ~


    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }        