AchaMeuPet\CoreBundle\Entity\Image:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        alt:
            type: string
            length: 255
        path:
            type: string
            length: 255
    lifecycleCallbacks: {  }
