AchaMeuPet\AchaMeuPet\CoreBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        facebookId:
            type: string
            legth: 255